spring.application.name=TaskFlow
server.port=8080
spring.datasource.url=jdbc:postgresql://postgres:SjpmhQGslhsTcZJczoTSAMNHJkNsSnev/railway
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=SjpmhQGslhsTcZJczoTSAMNHJkNsSnev
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=false